# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "홈"
  url = "#hero"
  weight = 10

[[main]]
  name = "글모음"
  url = "#posts"
  weight = 20

#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 30

# [[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 30

[[main]]
  name = "강의모음"
  url = "#courses"
  weight = 30

[[main]]
  name = "연락처"
  url = "#contact"
  weight = 40

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
#[[main]]
#  name = "CV"
#  url = "files/cv.pdf"
#  weight = 70
